### ISSUE TITLE
server not reachable

### ISSUE THREAD

**Issue by sethriel** [Kaljurand/K6nele-service#8]
The service just says "server not reachable" and that's it. Don't know what else to add here.

**Comment by Kaljurand** [comment]
Most likely it was a temporary issue on the server side, or do you still have this issue? Are you requesting a better explanation as part of the error message in the app why the server is not reachable, e.g. where exactly the connection gets broken? I guess this can be somewhat improved but hasn't been a priority.

**Comment by sethriel** [comment]
Hei,

Nime järgi julgen järeldada, et võib ka eesti keeles suhelda :) Probleem on
kahjuks püsiv ja mõte oli teenust kasutada dikteerimiseks, et saaks jutu
tekstina telefoni. Ei oska ka ise telefonist midagi rohkem näppida, et
katsetada teenust tööle saada. Kõik teised äpid/teenused saavad kenasti
võrku nii üle wifi kui 4G.

Ette tänades,
Andreas

**Comment by Kaljurand** [comment]
Kas oleks võimalik lisada siia mõni illustreeriv ekraanipilt vms. ning Androidi, Kõnele, ja Kõnele-service versiooniinfo. Hetkel on raske õelda, mis võiks katki olla.
